server:
  port: 9093

spring:
  application:
    name: AIRLINE-SERVICE
  datasource:
    url: jdbc:mysql://localhost:3306/Airlinedb
    password: root
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect



